### ISSUE TITLE
AttributeError: 'module' object has no attribute '_ElementInterface'

### ISSUE THREAD

**Issue by kyrias** [marianoguerra/rst2html5#62]
rst2html5 seems to be broken on py3.4, getting the same traceback from just running it without any command line options. Likely related to the same things as [this](http://sourceforge.net/p/docutils/bugs/255/) rst2odt bug report, unfortunately it doesn't point to what fixed it.

python 3.4.1
python-docutils 0.12

> Traceback (most recent call last):
  File "/usr/bin/rst2html5", line 9, in <module>
    load_entry_point('rst2html5-tools==0.2.3', 'console_scripts', 'rst2html5')()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2457, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2171, in load
    ['__name__'])
  File "/home/kyrias/build/rst2html5-git/a/html5css3/__init__.py", line 30, in <module>
    from . import html
  File "/home/kyrias/build/rst2html5-git/a/html5css3/html.py", line 13, in <module>
    class Element(ET._ElementInterface, object):
AttributeError: 'module' object has no attribute '_ElementInterface'

**Comment by torfsen** [comment]
Just got hit by this, too.

**Comment by marianoguerra** [comment]
can you check if that commit fixes your problem?

**Comment by torfsen** [comment]
For me it does fix the original problem, but I still run into problems with Python 3.4:

```
Traceback (most recent call last):
  File "./test.py", line 36, in <module>
    writer_name='html5css3',
  File "/home/torf/projects/rst2html5/venv3/lib/python3.4/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/home/torf/projects/rst2html5/venv3/lib/python3.4/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/home/torf/projects/rst2html5/venv3/lib/python3.4/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/home/torf/projects/rst2html5/venv3/lib/python3.4/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/torf/projects/rst2html5/html5css3/__init__.py", line 201, in translate
    visitor = self.translator_class(self.document)
  File "/home/torf/projects/rst2html5/html5css3/__init__.py", line 472, in __init__
    Title(self.title))
  File "/home/torf/projects/rst2html5/html5css3/html.py", line 212, in __init__
    TagBase.__init__(self, childs, attrs)
  File "/home/torf/projects/rst2html5/html5css3/html.py", line 58, in __init__
    self.append(child)
  File "/home/torf/projects/rst2html5/html5css3/html.py", line 64, in append
    if self._children:
AttributeError: 'Title' object has no attribute '_children'
```

The same code runs fine in Python 2.7.

**Comment by marianoguerra** [comment]
check now, I never tried it with python 3 until now, since I use it once in a while when I need to create a presentation, but now I fixed the problems until it ran, from now on it will be a matter of fixing stuff as it comes.

**Comment by torfsen** [comment]
Our basic test suite succeeds for me on Python 3.4 at 6fa6fde, so I guess the fundamental issues with Py3 have been resolved.

**Comment by marianoguerra** [comment]
:+1:
