### ISSUE TITLE
raw-directive has problems with multiple and nested tags

### ISSUE THREAD

**Issue by torfsen** [marianoguerra/rst2html5#72]
```
$ cat rst2html5_bug.rst 
.. raw:: html

    <div>foo</div><div>bar</div>

$ rst2html5 --traceback rst2html5_bug.rst
Traceback (most recent call last):
  File "/home/torf/projects/statika/venv/bin/rst2html5", line 9, in <module>
    load_entry_point('rst2html5-tools==0.2.6', 'console_scripts', 'rst2html5')()
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/main.py", line 33, in main
    description=description)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/core.py", line 352, in publish_cmdline
    config_section=config_section, enable_exit_status=enable_exit_status)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/__init__.py", line 200, in translate
    self.document.walkabout(visitor)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/__init__.py", line 806, in unknown_visit
    new_current = handler(node, self)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/__init__.py", line 330, in raw
    result = html.raw(node.astext())
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/html.py", line 245, in raw
    return Raw(content)
  File "/home/torf/projects/statika/venv/local/lib/python2.7/site-packages/html5css3/html.py", line 229, in __init__
    el = ET.fromstring(content)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: junk after document element: line 1, column 14
```
The problem is that the code in `html5css3.html.Raw.__init__` runs the `raw` content through `ElementTree.fromString`, which only accepts XML. Since the input in this case contains two elements without a common container it is not valid XML.

A quick workaround in the RST file is to simply surround the raw sections content with a container element (e.g. a `div`):
```
.. raw:: html

    <div><div>foo</div><div>bar</div></div>
```
This could also work for `html5css3.html.Raw.__init__` itself: Surround the content by a div and then remove the div from the information returned by `ElementTree.fromString`.

**Comment by torfsen** [comment]
I just noticed that while surrounding everything with a `div` fixes the crash it does show another problem: Nested tags are omitted. Given the RST
```
.. raw:: html

    <div><i>hello</i></div>
```
the produced HTML (without header, etc.) is
```
<body><div></div></body>
```
That is, the nested tag `<i>hello</i>` is dropped.

**Comment by torfsen** [comment]
The problem with nested tags is because the code in `html5css3.html.Raw.__init__` only extracts the tag, attributes and text from the raw content, and does not extract the child elements. This is easily fixed:
```
def __init__(self, content):
        el = ET.fromstring(content)
        Element.__init__(self, el.tag, el.attrib)
        for child in el:
            Element.append(self, child)
        self.text = el.text
        self.tail = el.tail
```
Instead of `Element.append(self, child)` one would normally use `self.append(child)`, however you've overwritten `append` to be a no-op and I'm therefore using the parent's method.

**Comment by marianoguerra** [comment]
hi, can you submit a PR with the proposed change? does it have any downside? thanks!

**Comment by torfsen** [comment]
I'll prepare PR, although it may take me time since things are pretty busy here at the moment.
